### ISSUE TITLE
Update air gapped script for 19x

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/driverlessai-recipes#109]
https://github.com/h2oai/driverlessai-recipes/tree/master/air-gapped_installations

@dhiyaneshwar please update master to call `set_username(username=<username>)` e.g. `<username>='h2oai'` because in DAI >=19x  every user has their own contrib folder.

**Comment by pseudotensor** [comment]
Error:

```
[ec2-user@ip-172-31-14-71 dai-1.9.0.1-linux-x86_64]$ ./dai-env.sh python load_custom_recipe.py -p ExampleLogTransformer.py >> load_custom_recipe.log
Traceback (most recent call last):
  File "load_custom_recipe.py", line 48, in <module>
    main()
  File "load_custom_recipe.py", line 37, in main
    server_load_all_custom_recipes(path=args.path)
  File "h2oaicore/recipe_server_support.py", line 129, in h2oaicore.recipe_server_support.server_load_all_custom_recipes
  File "h2oaicore/genes.py", line 3707, in h2oaicore.genes.GeneContribLoader.__init__
  File "h2oaicore/utils.py", line 433, in h2oaicore.utils.ContribLoader.__init__
  File "h2oaicore/systemutils.py", line 6808, in h2oaicore.systemutils.user_dir
ValueError: Missing or empty username: False
```
