### ISSUE TITLE
Issue with Nixtla_ARIMA, and Nixtla_ETS

### ISSUE THREAD

**Issue by tarique-husaain** [h2oai/driverlessai-recipes#193]
Model is running for evolution but fails while doing fix and refit .

From DAI logs:

Nixtla_Auto_ARIMA_Parallel failed: fit failure for NixtlaAutoARIMAParallelModel
cannot import name 'binary_join_element_wise' from 'pyarrow.compute' (/opt/h2oai/dai/python/lib/python3.8/site-packages/pyarrow/compute.py)

Single model failed, fix and refit experiment
Failed model: NixtlaAutoARIMAParallelModel

```
2024-02-16 10:22:06,559 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   | WARNING: predict for AutoARIMAParallelModel failed, skipping.  Error: [Traceback (most recent call last):
2024-02-16 10:22:06,560 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "h2oaicore/models_main.py", line 3755, in h2oaicore.models_main.MainModel.fit_base
2024-02-16 10:22:06,560 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "h2oaicore/models_main.py", line 3762, in h2oaicore.models_main.MainModel.fit_base
2024-02-16 10:22:06,560 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "../../../dai-data/nishals/contrib/models/autoarima_parallel_0b269fb7_content.py", line 479, in fit
2024-02-16 10:22:06,561 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |     mod = importlib.import_module("statsforecast.adapters.prophet")
2024-02-16 10:22:06,561 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "/opt/h2oai/dai/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2024-02-16 10:22:06,562 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |     return _bootstrap._gcd_import(name[level:], package, level)
2024-02-16 10:22:06,562 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2024-02-16 10:22:06,562 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2024-02-16 10:22:06,563 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
2024-02-16 10:22:06,563 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2024-02-16 10:22:06,564 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2024-02-16 10:22:06,564 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2024-02-16 10:22:06,565 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
2024-02-16 10:22:06,565 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2024-02-16 10:22:06,566 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2024-02-16 10:22:06,566 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2024-02-16 10:22:06,566 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2024-02-16 10:22:06,567 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2024-02-16 10:22:06,567 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2024-02-16 10:22:06,568 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2024-02-16 10:22:06,568 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "/dai-data/nishals/contrib/env/lib/python3.8/site-packages/statsforecast/__init__.py", line 3, in <module>
2024-02-16 10:22:06,568 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |     from .core import StatsForecast
2024-02-16 10:22:06,569 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "/dai-data/nishals/contrib/env/lib/python3.8/site-packages/statsforecast/core.py", line 23, in <module>
2024-02-16 10:22:06,569 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |     from triad import conditional_dispatcher
2024-02-16 10:22:06,570 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "/dai-data/nishals/contrib/env/lib/python3.8/site-packages/triad/__init__.py", line 4, in <module>
2024-02-16 10:22:06,570 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |     from triad.collections import FileSystem, IndexedOrderedDict, ParamDict, Schema
2024-02-16 10:22:06,571 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "/dai-data/nishals/contrib/env/lib/python3.8/site-packages/triad/collections/__init__.py", line 3, in <module>
2024-02-16 10:22:06,571 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |     from triad.collections.schema import Schema
2024-02-16 10:22:06,571 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "/dai-data/nishals/contrib/env/lib/python3.8/site-packages/triad/collections/schema.py", line 10, in <module>
2024-02-16 10:22:06,572 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |     from triad.utils.pandas_like import PD_UTILS
2024-02-16 10:22:06,572 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "/dai-data/nishals/contrib/env/lib/python3.8/site-packages/triad/utils/pandas_like.py", line 20, in <module>
2024-02-16 10:22:06,573 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |     from triad.utils.pyarrow import (
2024-02-16 10:22:06,573 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   File "/dai-data/nishals/contrib/env/lib/python3.8/site-packages/triad/utils/pyarrow.py", line 12, in <module>
2024-02-16 10:22:06,573 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |     from pyarrow.compute import CastOptions, binary_join_element_wise
2024-02-16 10:22:06,574 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   | ImportError: cannot import name 'binary_join_element_wise' from 'pyarrow.compute' (/opt/h2oai/dai/python/lib/python3.8/site-packages/pyarrow/compute.py)
2024-02-16 10:22:06,574 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   | ].
2024-02-16 10:22:06,575 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   Stack_file: [/dai-data/nishals/h2oai_experiment_cff0c076-ccb4-11ee-a0e8-02bab858771a/bf2cf24c-2ff2-4439-90fb-15fa7fd5a95f.stack]
2024-02-16 10:22:06,575 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    INFO   | [AutoARIMAProphet_Parallel] (11, 2) model predict shape=(11, 2) threads=1 end. Took 0.01746 seconds.
2024-02-16 10:22:06,576 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    INFO   | [AutoARIMAProphet_Parallel] model predict_with_transform shape=(11, 4) threads=1 end. Took 0.02458 seconds.
2024-02-16 10:22:06,687 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    INFO   | [AutoARIMAProphet_Parallel] model fit shape=(18, 2) threads=1 start.
2024-02-16 10:22:06,688 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    INFO   | Start Fitting autoarima Model with params : {'growth': 'linear', 'seasonality_mode': 'additive', 'country_holidays': None, 'weekly_seasonality': 'auto', 'monthly_seasonality': False, 'quarterly_seasonality': False, 'yearly_seasonality': 'auto'}
2024-02-16 10:22:06,689 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    INFO   | autoarima will use 50 groups as well as average target data.
2024-02-16 10:22:06,699 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    INFO   | autoarima temp folder /dai-data/nishals/h2oai_experiment_cff0c076-ccb4-11ee-a0e8-02bab858771a/a0a56cf1-397a-4dd8-927b-3562fec92212_autoarima_model_folder
2024-02-16 10:22:06,771 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    INFO   | [AutoARIMAProphet_Parallel] model fit shape=(18, 2) threads=1 end. Took 0.08115 seconds.
2024-02-16 10:22:06,772 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    WARNING| fit failure for AutoARIMAParallelModel failed, skipping.
2024-02-16 10:22:06,772 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    WARNING|   Stack_file: [/dai-data/nishals/h2oai_experiment_cff0c076-ccb4-11ee-a0e8-02bab858771a/17f70d39-3d8d-480f-ba41-023898dadece.stack]
2024-02-16 10:22:06,773 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   | WARNING: fit failure for AutoARIMAParallelModel failed, skipping.  Error: [  File "/dai-data/nishals/contrib/env/lib/python3.8/site-packages/triad/utils/pyarrow.py", line 12, in <module>
2024-02-16 10:22:06,773 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |     from pyarrow.compute import CastOptions, binary_join_element_wise
2024-02-16 10:22:06,774 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   | ImportError: cannot import name 'binary_join_element_wise' from 'pyarrow.compute' (/opt/h2oai/dai/python/lib/python3.8/site-packages/pyarrow/compute.py)].
2024-02-16 10:22:06,774 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    DATA   |   Stack_file: [/dai-data/nishals/h2oai_experiment_cff0c076-ccb4-11ee-a0e8-02bab858771a/17f70d39-3d8d-480f-ba41-023898dadece.stack]
2024-02-16 10:22:07,168 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    INFO   | [AutoARIMAProphet_Parallel] model predict_with_transform shape=(11, 4) threads=1 start.
2024-02-16 10:22:07,169 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    INFO   | [AutoARIMAProphet_Parallel] (11, 2) model predict shape=(11, 2) threads=1 start.
2024-02-16 10:22:07,170 C: 10% D:9.7GB   M:7.3GB   NODE:LOCAL1      103    WARNING| predict for AutoARIMAParallelModel failed, skipping.
```

Attaching files for reproducibility.

[Archive.zip](https://github.com/h2oai/driverlessai-recipes/files/14328627/Archive.zip)

**Comment by tarique-husaain** [comment]
@AzulGarza would like your team to review it and suggest the required modifications.

**Comment by iamakalia** [comment]
@AzulGarza Can someone please review this and suggest.
